### ISSUE TITLE
Custom commands modules

### ISSUE THREAD

**Issue by naterchrdsn** [Spudnik-Group/Spudnik#125]
the ability to create a custom command would be extremely useful.

similar to custom commands here: https://github.com/Mantaro/MantaroBot/wiki/Command-reference-and-documentation#utility-commands

and here: https://github.com/Mantaro/MantaroBot/wiki/Custom-Commands

**Comment by develogix** [comment]
I'm not sure we can tag the `1.0.0` milestone on this; the underlying function needed is why the starboard functionality is currently broken.

Needs further research to figure out what event emitter to attach a callback to.

**Comment by develogix** [comment]
closed by #327
