### ISSUE TITLE
Feature Request: Reaction Roles

### ISSUE THREAD

**Issue by cwchristerw** [Spudnik-Group/Spudnik#238]
I want similar kind of feature like Carl Bot has (https://docs.carl.gg/roles/reaction-roles/)

**Comment by cwchristerw** [comment]
This might be starting point https://github.com/Sam-DevZ/Discord-RoleReact

**Comment by naterchrdsn** [comment]
Closing this for this to be voted on and prioritized on our feathub: https://feathub.com/Spudnik-Group/Spudnik/+17
