### ISSUE TITLE
role module issues

### ISSUE THREAD

**Issue by develogix** [Spudnik-Group/Spudnik#37]
~~[Removed]~~ - Today at 3:50 PM
!role add pubg
Spudnik - Today at 3:50 PM
~~[Removed]~~, An error occurred while running the command: TypeError: guildAssignableRoles.indexOf is not a function
You shouldn't ever receive an error like this.
Please contact ~~[Removed]~~.

**Comment by develogix** [comment]
this happens with both text and uuid references to role names

**Comment by naterchrdsn** [comment]
!role list in a server with no default role and no assignable roles still shows the embed.

!role default with no role mention sets the default role to undefined

other subcommands with undefined secondary args accept undefined input
