### ISSUE TITLE
streamer monitoring

### ISSUE THREAD

**Issue by naterchrdsn** [Spudnik-Group/Spudnik#63]
auto-announce people going live on this list

* smashcast
* twitch
* mixer
* list streams
* remove/add streams

also, 
* command for: Sets a role which is monitored for streamers (FromRole), and a role to add if a user from 'FromRole' is streaming (AddRole). When a user from 'FromRole' starts streaming, they will receive an 'AddRole'. Provide no parameters to disable
* Sets keyword which is required in the stream's title in order for the streamrole to apply. Provide no keyword in order to reset.
* Adds or removes a blacklisted user. Blacklisted users will never receive the stream role.
* Adds or removes a whitelisted user. Whitelisted users will receive the stream role even if they don't have the specified keyword in their stream title.

**Comment by develogix** [comment]
closed by #327
