### ISSUE TITLE
Standardization

### ISSUE THREAD

**Issue by naterchrdsn** [Spudnik-Group/Spudnik#68]
* Modules
-- All modules should have a good description (in normal casing)
-- If a module has args, we should use the `detail` field to explain each possible option on multiple lines, and display the command with optional and required args at the top of the detail field
-- all modules should have example command combinations
-- Failed settings changes should use `sendSimpleEmbeddedError` method, with expiry
-- add validation to command args where applicable, with descriptive error messages.
-- standardize all modules that do a request, and make sure there is a "loading" status, only message as return type for run function, and make sure there is consistent error reporting and responses for different statuses
-- ensure embeds are relevant
-- ensure permissions checks are relevant.
-- change all `console` statements to use the commandoClient `warn`,`error`, and `debug` event emitters, this will standardize all error logging

**Comment by naterchrdsn** [comment]
error handling and request syntax for modules that do requests:
```

		const response = await sendSimpleEmbeddedMessage(msg, 'Loading...');
		const options = {
			method: 'GET',
			uri: 'http://imgs.xkcd.com/comics/now.png',
			followAllRedirects: true,
			json: true,
		};

		rp(options)
			.then((resp) => {
				if (resp.uri.href) {
					msg.delete();
					return sendSimpleEmbeddedImage(msg, resp.uri.href.toString());
				} else {
					msg.delete();
					msg.client.emit('warn', `Unsuccessful request.\nCommand: 'highnoon'\nContext: ${resp}`);
					return sendSimpleEmbeddedError(msg, 'There was an error with the request. Try again?', 300);
				}
			})
			.catch((err) => {
				msg.delete();
				msg.client.emit('error', `Error with command 'highnoon'\nError: ${err}`);
				return sendSimpleEmbeddedError(msg, 'There was an error with the request. Try again?', 300);
			});
		return response;```

**Comment by develogix** [comment]
- Move status and discord bot list update intervals to `config.json`

**Comment by develogix** [comment]
- Fix the feathub image in `README.md`

**Comment by naterchrdsn** [comment]
@develogix should we make the option to delete all command messages a toggle-able one?

**Comment by naterchrdsn** [comment]
all links provided in a bot response should be enclosed in `< >` so that the link preview doesn't show and take up space

**Comment by naterchrdsn** [comment]
all modules with subcommands should accept an arguement passed in to trigger a change, rather than doing an action when ran in a certain channel.

for example: the starboard command currently needs to have the `!starboard channel` command run inside of the channel to be used, this command should instead accept a channel id.

**Comment by naterchrdsn** [comment]
error emit format: `msg.client.emit('warn', `Error in command misc:unshort: ${err}`);`

**Comment by naterchrdsn** [comment]
Last of items to do:
- all modules that use a third party lib should use promises instead
- add testing and deployment in appveyor to azure, github pages, and github releases
- ensure base classes have proper error handling and checking
